In [ ]:
import torch

depth, rows, d, e = 2, 3, 4, 2
column = d * e  
x = torch.randn(depth, rows, column)

# Reshape
x_reshaped = x.view(depth, rows, d, e)

print(x,'\n\n\n',x_reshaped)

tensor([[[-1.2528, -0.6832,  0.4292, -0.3244, -0.2148,  0.1207,  0.8213,
           0.2998],
         [-1.5102,  1.6797, -0.9782,  0.3902, -0.4488,  0.9430, -0.2317,
           0.2318],
         [-0.7845, -0.4332,  0.0965,  0.0746, -0.7600, -0.7485,  0.4946,
          -1.8669]],

        [[-0.1685, -0.2116, -1.1731,  0.1507,  1.3386,  0.0426, -1.1282,
          -0.1306],
         [ 0.9799, -1.7662, -0.5427, -0.5192, -0.6469,  0.1114, -0.2555,
           0.2242],
         [-0.6767, -1.0849,  1.0593, -1.7978, -0.7648, -2.0527, -1.2144,
          -0.4801]]]) 


 tensor([[[[-1.2528, -0.6832],
          [ 0.4292, -0.3244],
          [-0.2148,  0.1207],
          [ 0.8213,  0.2998]],

         [[-1.5102,  1.6797],
          [-0.9782,  0.3902],
          [-0.4488,  0.9430],
          [-0.2317,  0.2318]],

         [[-0.7845, -0.4332],
          [ 0.0965,  0.0746],
          [-0.7600, -0.7485],
          [ 0.4946, -1.8669]]],


        [[[-0.1685, -0.2116],
          [-1.1731,  0.1507],
      

In [12]:
import torch

rows, d, e = 3, 4, 2
column = d * e  
x = torch.randn(rows, column)

# Reshape
x_reshaped = x.view(rows, d, e)

print(x,'\n\n\n',x_reshaped)

tensor([[ 0.1682, -3.1871,  1.1635, -0.0122,  0.4925,  1.5029,  0.3056,  0.0094],
        [-0.7474,  0.3151, -0.4666,  1.8834,  1.2925, -0.4317,  0.7600,  0.1197],
        [ 1.7020,  0.0387,  0.2797, -0.2038, -0.5087,  0.3497, -0.6792,  2.4783]]) 


 tensor([[[ 0.1682, -3.1871],
         [ 1.1635, -0.0122],
         [ 0.4925,  1.5029],
         [ 0.3056,  0.0094]],

        [[-0.7474,  0.3151],
         [-0.4666,  1.8834],
         [ 1.2925, -0.4317],
         [ 0.7600,  0.1197]],

        [[ 1.7020,  0.0387],
         [ 0.2797, -0.2038],
         [-0.5087,  0.3497],
         [-0.6792,  2.4783]]])
